[package]
name = "winter"
version = "0.1.0"
edition = "2021"
authors = ["ArcticSpaceFox contact@spacefoxlabs.com"]
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.51"
itertools = "0.10.1"
thiserror = "1.0.30"
clap = "2.34.0"
